# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GSI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GSI
pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Storage', '~> 5.15.0'
  target 'GSI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GSITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GSI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GSI-tvOS

  

end
